version: '3.8'

services:
  web:
    build: .
    image: yy3401/5-final-project-spring-2024-zuihouyige-web:latest
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: